kind: Service
apiVersion: v1
metadata:
  name: helidon
  labels:
    app: helidon
spec:
  type: ClusterIP
  selector:
    app: helidon
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon
  template:
    metadata:
      labels:
        app: helidon
        version: v1
    spec:
      containers:
      - name: helidon
        image: helidon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
